config/routes.rb
Rails.application.routes.draw do
  get "blogs/index"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'users' =>'users#index'
  get 'posts/music' => 'posts#music'
  get 'posts/video' => 'posts#video'
  get "mypage", to: "users#show", as: :mypage


  resources :users, only: [:show] do
  member do
    get :comments_list
  end
end
 # ユーザーマイページへのルーティング

  root to: 'tweets#index'
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:index, :create]
    get :comments_list, on: :member
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :content, presence: true   # ← 空を禁止
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    
def start_time
  created_at
end
    
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy

  validates :name, presence: true #追記
  validates :profile, length: { maximum: 170 } #追記


  has_one_attached :profile_image

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

  before_validation :normalize_started_at

private
def normalize_started_at
  if started_at.is_a?(String) && started_at.match?(/^\d{4}$/)
    self.started_at = Date.new(started_at.to_i, 1, 1)
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 割愛

  # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時に許可するパラメータ
    devise_parameter_sanitizer.permit(
  :sign_up,
  keys: [:name, :image, :started_at, :role, :creator_type]
)

    # アカウント編集時に許可するパラメータ
    devise_parameter_sanitizer.permit(
  :account_update,
  keys: [:name, :profile, :profile_image, :x_url, :instagram_url,
         :facebook_url, :youtube_url, :started_at, :role, :creator_type]
)

  end

  def after_update_path_for(resource)
    tweets_path
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

 def index
  @tweet = Tweet.find(params[:tweet_id])
  @comments = @tweet.comments

  render partial: "comments/comments_list", locals: { comments: @comments, tweet: @tweet }
end


def create
  @tweet = Tweet.find(params[:tweet_id])
  @comment = @tweet.comments.build(comment_params)
  @comment.user = current_user

  if @comment.save
      redirect_to mypage_path, notice: "コメントしました"
    else
      render "tweets/show", status: :unprocessable_entity
    end
  end

def comments_list
  @tweet = Tweet.find(params[:id])
  @comments = @tweet.comments.includes(:user)
  @comment = Comment.new

  if params[:from] == "mypage"
    render partial: "comments/mypage_comments_list", locals: { tweet: @tweet, comment: @comment }
  else
    render partial: "comments/comments_list", locals: { tweet: @tweet, comment: @comment }
  end
end



private

def comment_params
  params.require(:comment).permit(:content)
end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end

# 追記ここから
  def link
  end
#ここまで
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_to params[:return_to] || root_path
    end

    def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_to params[:return_to] || root_path
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    # 基本のツイート（User と一緒に取得）
    @tweets = Tweet.joins(:user).includes(:user).order(created_at: :desc)
    @rank_tweets = Tweet.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}

    # 部分検索
    if params[:search].present?
      @tweets = @tweets.where("tweets.body LIKE ?", "%#{params[:search]}%")
    end

     # カテゴリーで絞り込み
    if params[:category].present?
      @tweets = @tweets.where(category: params[:category])
    end
    
    # 活動年数での絞り込み
if params[:active_years].present?
  today = Date.today

  @tweets = @tweets.select do |tweet|
    next false unless tweet.user&.started_at

    # 実際の経過年数（日付差で計算）
    active_years = ((today - tweet.user.started_at) / 365.25).floor

    case params[:active_years]
    when "0-1"
      active_years < 1                     # 1年未満
    when "1-4"
      (1..3).cover?(active_years)          # 1年以上4年未満
    when "4-10"
      (4..9).cover?(active_years)          # 4年以上10年未満
    when "10+"
      active_years >= 10                   # 10年以上
    else
      true
    end
  end
end

  # 最近投稿された動画（YouTubeあり）を直近30件
  @recent_videos = Tweet.where.not(youtube_url: nil)
                        .order(created_at: :desc)
                        .limit(20)

  # いいね数ランキングを上位20件
  @rank_tweets = Tweet.all.sort { |a, b| b.liked_users.count <=> a.liked_users.count }
                          .first(20)
  end  # ← ここが index の end
  

  def new
    @tweet = Tweet.new
  end

  def show
    @tweet = Tweet.find(params[:id])

    @comments = @tweet.comments
    @comment = Comment.new
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id

    if tweet.save
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end

  # カテゴリー分けに関連するところのみ記載
  def music
    @Tweets = Post.all
  end

  def video
    @Tweets = Post.all
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to action: "show", id: tweet.id
    else
      redirect_to action: "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

def comments_list
  @tweet = Tweet.find(params[:id])
  @comments = @tweet.comments.includes(:user)
  render partial: "comments/comments_list", locals: { tweet: @tweet, comments: @comments }
end


  private

  def tweet_params
  params.require(:tweet).permit(:body, :image, :youtube_url, :cotent, :category)
end
end

app/controllers/users/registrations_controller.rb
# app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected
  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  @user = User.find(params[:id])
  @tweets = @user.tweets.order(created_at: :desc)
end

  def active_years
    return nil unless started_at
    now = Date.today.year
    (now - started_at.year)
  end

  def active_tag
    return nil unless active_years
    case active_years
    when 0..2
      "0〜3年目"
    when 3..4
      "3〜5年目"
    when 5..9
      "5〜10年目"
    else
      "10年以上"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SimpleCalendar::ViewHelpers
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def find_youtube_url(youtube_url)
    return nil if youtube_url.blank?  # nilや空文字なら即return

    if youtube_url[0..16] == "https://youtu.be/"
      youtube_url[17..27] # 11桁の動画IDを返す
    else
      nil
    end
  end
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/blogs/index.html.erb
<h1>Blogs#index</h1>
<p>Find me in app/views/blogs/index.html.erb</p>

app/views/comments/_comments_list.html.erb
<%= form_with(model: [tweet, Comment.new], local: true, class: "comment-form") do |f| %>

  
  <div>
    <%= f.text_area :content, rows: 3, placeholder: "コメントを入力...", required: true %>
  </div>
  <div>
    <%= f.submit "送信", class: "btn-submit" %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [tweet, comment], local: true, class: "comment-form") do |f| %>
  <%= hidden_field_tag :from, from %> <!-- 共通で1回書けばOK -->

  <div>
    <%= f.text_area :content, rows: 3, placeholder: "コメントを入力...", required: true %>
  </div>
  <div>
    <%= f.submit "送信", class: "btn-submit" %>
  </div>
<% end %>

  <div class="comments-list">
    <% tweet.comments.each do |c| %>
      <p><strong><%= c.user.name %>:</strong> <%= c.content %></p>
    <% end %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.replace "comments_#{@tweet.id}" do %>
  <%= render partial: "comments/comments_list",
             locals: { tweet: @tweet, comment: Comment.new } %>
<% end %>

app/views/hello/index.html.erb
<%= link_to "ログイン", tweets_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is GeekSalon.
<%= link_to 'トップページ', hello_index_path %> 

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, :size => 140 %> 
  <br>
    <%= f.label :youtube_url, "YouTube URL" %>
    <%= f.text_field :youtube_url, size: 140 %>

    <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

    <%= f.select :category, [["音楽", "music"], ["動画", "video"]], include_blank: "どの投稿？" %>
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<div class="page-banner">
  <%= image_tag "headerイメージ.jpg", class: "banner-image" %>
</div>
<h3>Tweet一覧</h3>

<h3>投稿を検索</h3>
<%= form_tag({controller: "tweets", action: "index"}, method: :get, class: "search-form") do %>
  <!-- 上段：検索文字列 -->
  <div class="search-row">
    <%= text_field_tag :search, params[:search], placeholder: "キーワードで検索", class: "search-input" %>
  </div>

  <!-- 下段：セレクトボックス2つ＋検索ボタン -->
  <div class="filter-row">
    <%= select_tag :active_years, 
      options_for_select([
        ["1年未満", "0-1"],
        ["1〜4年未満", "1-4"],
        ["4〜10年未満", "4-10"],
        ["10年以上", "10+"]
      ], params[:active_years]),
      include_blank: "活動年数で絞り込み",
      class: "filter-select" %>

    
    <%= select_tag :category,
      options_for_select([
          ["画像", "image"],
          ["動画", "video"],
          ["音楽", "music"]
        ], params[:category]),
      include_blank: "メディアで絞り込み",
      class: "filter-select",
      onchange: "this.form.submit();" %>

    <%= submit_tag '検索する', class: "search-button" %>
  </div>
<% end %>



<h2>最近投稿された動画</h2>
<div class="recent-videos">
  <% @recent_videos.each do |t| %>
    <% if (youtube_id = find_youtube_url(t.youtube_url)) %>
      <div class="video-card">
      <div class="video-user">
          <% if t.user.profile_image.attached? %>
            <%= image_tag t.user.profile_image, size: '40x40', class: "profile-icon" %>
          <% end %>
          <%= link_to t.user.name, user_path(t.user), class: "profile-name" %>
        </div>
        <iframe width="250" height="150"
          src="https://www.youtube.com/embed/<%= youtube_id %>"
          frameborder="0" allowfullscreen>
        </iframe>
      </div>
    <% end %>
  <% end %>
</div>

<h2>人気の投稿</h2>
<div class="rank-tweets">
  <% @rank_tweets.each do |t| %>
    <div class="rank-card">

      <!-- プロフィール画像＋名前 -->
      <div class="rank-user">
        <% if t.user.profile_image.attached? %>
          <%= image_tag t.user.profile_image, size: '40x40', class: "profile-icon" %>
        <% end %>
        <%= link_to t.user.name, user_path(t.user), class: "profile-name" %>
      </div>

      <!-- 投稿内容（動画 / 画像 / テキスト） -->
      <% if (youtube_id = find_youtube_url(t.youtube_url)) %>
        <iframe width="250" height="150"
          src="https://www.youtube.com/embed/<%= youtube_id %>"
          frameborder="0" allowfullscreen>
        </iframe>
      <% elsif t.image.attached? %>
        <%= image_tag t.image, size: "250x150", class: "rank-image" %>
      <% else %>
        <p class="rank-text"><%= truncate(t.body, length: 50) %></p>
      <% end %>

      <!-- いいね数 -->
      <span class="like-count">❤️ <%= t.likes.count %></span>
    </div>
  <% end %>
</div>

<div class="main-container">
  <!-- 左：カレンダー -->
  <div class="calendar-section">
    <h1>投稿カレンダー</h1>
    <%= month_calendar(events: @tweets, date_method: :created_at, start_day: :mon) do |date, tweets| %>
      <div class="day">
        <div class="date"><%= date.day %></div>
        <strong><%= tweets.count %></strong>
      </div>
    <% end %>
  </div>

  
<div class="tweets-container">
  <h2>最新の投稿</h2>
  <% @tweets.each do |t| %>
    <div class="tweet">

      <!-- プロフィール画像と名前 -->
      <div class="tweet-user">
        <% if t.user.profile_image.attached? %>
          <%= image_tag t.user.profile_image, size: '50x50', class: "profile-icon" %>
        <% end %>
        <%= link_to t.user.name, user_path(t.user.id), class: "profile-name" %>
      </div>

      <!-- 投稿本文 -->
      <div class="tweet-body">
        <%= t.body %>
      </div>

      <div class="media-wrapper">
  <!-- 投稿画像 -->
  <% if t.image.attached? %>
    <%= image_tag t.image, class: "media-content" %>
  <% end %>

  <!-- 投稿動画 -->
  <% if (youtube_id = find_youtube_url(t.youtube_url)) %>
    <iframe
      class="media-content"
      src="https://www.youtube.com/embed/<%= youtube_id %>"
      frameborder="0" allowfullscreen>
    </iframe>
  <% end %>
</div>
  
<!-- いいねボタン -->
      <div class="tweet-likes">
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to tweet_like_path(t, t.likes.find_by(user: current_user)),
                          method: :delete,
                          params: { return_to: request.fullpath },
                          class: "like-button" do %>
              <i class="fas fa-heart liked"></i>
            <% end %>
          <% else %>
            <%= button_to tweet_likes_path(t),
                          method: :post,
                          params: { return_to: request.fullpath },
                          class: "like-button" do %>
              <i class="far fa-heart"></i>
            <% end %>
          <% end %>
          <span class="like-count"><%= t.likes.count %></span>
        <% else %>
          <i class="far fa-heart"></i>
          <span class="like-count"><%= t.likes.count %></span>
        <% end %>
      </div>


      <!-- フッター -->
<div class="tweet-footer">
  <p class="time">
    <%= t.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M") %>
  </p>

  <div class="action-buttons-footer">

  <!-- コメントボタン -->
<div class="comment-button">
  <a href="#" class="open-comment-modal" data-tweet-id="<%= t.id %>" data-from="home">
    <i class="far fa-comments"></i>
    <span id="comment_count_<%= t.id %>"><%= t.comments.size %></span>
  </a>
</div>


<% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to tweet_path(t), class: "btn-detail" do %>
        <i class="fas fa-sticky-note"></i> 詳細
      <% end %>

      <%= button_to tweet_path(t),
      method: :delete,
      class: "btn-delete",
      onclick: "return confirm('本当に削除しますか？');" do %>
  <i class="fas fa-trash-alt"></i> 削除
<% end %>

    </div>
  <% end %>
</div> <!-- /.tweet-footer -->
<% end %>

<br>
<br>

app/views/tweets/music.html.erb
<h1>音楽系投稿</h1>
<% @Tweets.each do |t| %>
  <% if t.category == "music" %> 
  <p>内容:<%= t.content %></p>
  <% end %>
<% end %>

app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
    <p class="title">投稿フォーム</p>
    <%= form_for(@tweet, :url => { controller:'tweets', action:'create'})do |f| %>
    <%= f.label :投稿内容 %>
        <br>
        <%= f.text_field :body,size: 140%>
        <br>
    <%= f.label :youtube_url, "YouTube URL" %>
    <%= f.text_field :youtube_url, size: 140 %>

    <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="form-group category-field">
  <%= f.label :category, "投稿カテゴリ" %>
  <%= f.select :category, [["画像", "image"], ["動画", "video"], ["音楽", "music"]],
               include_blank: "どの投稿？",
               class: "category-select" %>
</div>



<div class="form-group">
  <%= f.label :completed, "完成版か未完成か" %>
  <div class="toggle-wrapper">
    <%= f.check_box :completed, class: "toggle-checkbox", id: "completed-toggle" %>
    <label for="completed-toggle" class="toggle-label"></label>
  </div>
  <span id="completed-status">
  <%= f.object.completed? ? "完成" : "未完成" %>
  </span>

</div>

<%= f.submit "投稿" %>
  <br>
    <% end %>


</div>

app/views/tweets/show.html.erb
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at.in_time_zone("Tokyo").strftime("%Y/%m/%d %H:%M") %></p>

  <% if @tweet.youtube_url.present? || @tweet.image_url.present? %>
  <div class="tweet-media">
    <% if @tweet.youtube_url.present? %>
      <iframe width="30%" height="30%"
              src="https://www.youtube.com/embed/<%= find_youtube_url(@tweet.youtube_url) %>"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen>
      </iframe>
    <% end %>

    <% if @tweet.image_url.present? %>
      <%= image_tag @tweet.image_url, alt: "投稿画像", class: "tweet-image" %>
    <% end %>
  </div>
<% end %>

<div class="tweet-likes">
  <% if user_signed_in? %>
    <% like = current_user.likes.find_by(tweet_id: @tweet.id) %>
    <% if like %>
      <%= button_to tweet_like_path(@tweet, like),
                    method: :delete,
                    params: { return_to: request.fullpath },
                    class: "like-button" do %>
        <i class="fas fa-heart liked"></i>
      <% end %>
    <% else %>
      <%= button_to tweet_likes_path(@tweet),
                    method: :post,
                    params: { return_to: request.fullpath },
                    class: "like-button" do %>
        <i class="far fa-heart"></i>
      <% end %>
    <% end %>
    <span class="like-count"><%= @tweet.likes.count %></span>
  <% else %>
    <i class="far fa-heart"></i>
    <span class="like-count"><%= @tweet.likes.count %></span>
  <% end %>
</div>

 <%= link_to "編集する", edit_tweet_path(@tweet.id), class: "edit-tweet-link" %>

<h2 class="liked-users-title">いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.name %></li>
<% end %>

<!-- コメント一覧 -->
<h2 class="comments-title">コメント</h2>
<div class="comments-list">
  <% @tweet.comments.each do |comment| %>
  <div class="comment">
    <!-- プロフィール画像と名前 -->
    <div class="comment-user">
      <% if comment.user&.profile_image&.attached? %>
        <%= image_tag comment.user.profile_image, size: '50x50', class: "profile-icon" %>
      <% end %>
      <strong><%= comment.user&.name || "profile-name" %></strong>
    </div>

    <!-- コメント内容 -->
    <div class="comment-content">
      <p><%= comment.content %></p>
      <small><%= comment.created_at.in_time_zone("Asia/Tokyo").strftime("%Y/%m/%d %H:%M") %></small>
    </div>
  </div>
<% end %>

<%= link_to "Tweet一覧に戻る", tweets_path %>

<br>
<br>
<br>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="page-banner">
  <%= image_tag "headerイメージ.jpg", class: "banner-image" %>
</div>

<div class="user-page-container">

  <!-- 左カラム（プロフィール部分） -->
  <div class="user-left">
    <% if @user.profile_image.attached? %>
      <%= image_tag @user.profile_image, size: '200x200', class: "profile-img" %>
    <% end %>

    <h1 class="user-name"><%= @user.name %></h1>
    <p class="user-bio"><%= @user.profile.presence || "プロフィールは未設定です" %></p>

    <div class="user-socials">
      <% if @user.x_url.present? %>
        <%= link_to @user.x_url, target: "_blank" do %>
          <i class="fab fa-twitter"></i>
        <% end %>
      <% end %>
      <% if @user.instagram_url.present? %>
        <%= link_to @user.instagram_url, target: "_blank" do %>
          <i class="fab fa-instagram"></i>
        <% end %>
      <% end %>
      <% if @user.facebook_url.present? %>
        <%= link_to @user.facebook_url, target: "_blank" do %>
          <i class="fab fa-facebook"></i>
        <% end %>
      <% end %>
      <% if @user.youtube_url.present? %>
        <%= link_to @user.youtube_url, target: "_blank" do %>
          <i class="fab fa-youtube"></i>
        <% end %>
      <% end %>
    </div>

    <% if current_user.id == @user.id %>
      <%= link_to "プロフィール編集", edit_user_registration_path, class: "btn-edit" %>
    <%= link_to "ログアウト",
            destroy_user_session_path,
            method: :delete,
            data: { confirm: "ログアウトしますか？" },
            class: "btn-logout" %>
    <% end %>
  </div>

<div class="user-right">
  <h2>投稿一覧</h2>
  <div class="tweets-container">
     <% @tweets.each do |t| %>
    <div class="tweet">

      <!-- プロフィール画像と名前 -->
      <div class="tweet-user">
        <% if t.user.profile_image.attached? %>
          <%= image_tag t.user.profile_image, size: '50x50', class: "profile-icon" %>
        <% end %>
        <%= link_to t.user.name, user_path(t.user.id), class: "profile-name" %>
      </div>

      <!-- 投稿本文 -->
      <div class="tweet-body">
        <%= t.body %>
      </div>

      <div class="media-wrapper">
  <!-- 投稿画像 -->
  <% if t.image.attached? %>
    <%= image_tag t.image, class: "media-content" %>
  <% end %>

  <!-- 投稿動画 -->
  <% if (youtube_id = find_youtube_url(t.youtube_url)) %>
    <iframe
      class="media-content"
      src="https://www.youtube.com/embed/<%= youtube_id %>"
      frameborder="0" allowfullscreen>
    </iframe>
  <% end %>
</div>


      <!-- いいねボタン -->
      <div class="tweet-likes">
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= button_to tweet_like_path(t, t.likes.find_by(user: current_user)),
                          method: :delete,
                          params: { return_to: request.fullpath },
                          class: "like-button" do %>
              <i class="fas fa-heart liked"></i>
            <% end %>
          <% else %>
            <%= button_to tweet_likes_path(t),
                          method: :post,
                          params: { return_to: request.fullpath },
                          class: "like-button" do %>
              <i class="far fa-heart"></i>
            <% end %>
          <% end %>
          <span class="like-count"><%= t.likes.count %></span>
        <% else %>
          <i class="far fa-heart"></i>
          <span class="like-count"><%= t.likes.count %></span>
        <% end %>
      </div>

      <!-- フッター -->
<div class="tweet-footer">
  <p class="time">
    <%= t.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M") %>
  </p>

  <div class="action-buttons-footer">
  <!-- コメントボタン -->
  <div class="comment-button">
  <a href="#" class="open-comment-modal" data-tweet-id="<%= t.id %>" data-from="mypage">
    <i class="far fa-comments"></i>
    <span id="comment_count_<%= t.id %>"><%= t.comments.size %></span>
  </a>
  </div>


<%= turbo_frame_tag "comments_#{t.id}" %>
  <!-- 初期状態では空。クリックしたらここにコメント一覧 + フォームが差し込まれる -->


  <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to tweet_path(t), class: "btn-detail" do %>
        <i class="fas fa-sticky-note"></i> 詳細
      <% end %>

      <%= button_to tweet_path(t),
      method: :delete,
      class: "btn-delete",
      onclick: "return confirm('本当に削除しますか？');" do %>
  <i class="fas fa-trash-alt"></i> 削除
<% end %>

    </div>
  <% end %>
</div> <!-- /.tweet-footer -->
<% end %>